mysql.url=${DATABASE_MYSQL_URL:localhost:3306}
mysql.schema=${DATABASE_MYSQL_SCHEMA:codeflix_admin_catalog_db}
mysql.username=${DATABASE_MYSQL_USERNAME:root}
mysql.password=${DATABASE_MYSQL_PASSWORD:123456}