server.undertow.threads.worker=10
server.undertow.threads.io=2

mysql.url=localhost:3306
mysql.schema=codeflix_admin_catalog_db
mysql.username=root
mysql.password=123456

spring.jpa.properties.hibernate.generate_statistics=true

spring.jpa.show-sql=true
