version: "3"

services:
  codeflix-admin-app:
    image: fredsonchaves07/codeflix-adm-catalog:latest
    container_name: codeflix-admin-dev-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - PROFILE_ACTIVE=prod
    links:
      - codeflix-admin-database
    depends_on:
      - codeflix-admin-database


  codeflix-admin-database:
    image: mysql:latest
    container_name: codeflix-admin-database
    env_file:
      - .env
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_ROOT_PASSWORD}
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - coeflix-admin-network

networks:
  coeflix-admin-network: