name: CI CodeFlix Prd

on:
  pull_request:
    branches: [ "main" ]

jobs:
  java:
    name: CI prod job codeflix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build app
        run: mvn clean package -DskipTests

      - name: Run tests
        env:
          PROFILE_ACTIVE: 'test'
        run: mvn clean install

      - name: Credentials Github
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}